"""Reviewed editorial migration. Run explicitly; not part of normal site build."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
# name | neighbourhood | area | cuisine | headline | scope | policy | source
ROWS = '''Noble Rot Soho|Soho|Central|French & European|£35 per 750ml|public|Let the restaurant know in advance. No bottle limit or magnum price established in the published FAQ.|https://noblerot.co.uk/faq
Noble Rot Mayfair|Mayfair|Central|French & European|£35 per 750ml|public|Let the restaurant know in advance. No separate magnum charge established.|https://noblerot.co.uk/faq
Noble Rot Lamb’s Conduit|Bloomsbury|Central|French & European|£35 per 750ml|public|Let the restaurant know in advance. The group FAQ applies; bottle limits are not specified.|https://noblerot.co.uk/faq
Kitchen W8|Kensington|West|Modern European|£30 · free Sunday evening|public|One bottle per two guests, maximum four per booking. No Saturday evening corkage. Sunday evening is free except special events, Valentine’s Day and New Year’s Eve. Discuss bottles and glassware when booking.|https://www.kitchenw8.com/wine/
Medlar|Chelsea|West|French & European|£20 lunch / £40 dinner|public|Rates per 75cl bottle. No bottle limit; email in advance. Larger formats and sparkling terms should be checked separately.|https://www.medlarrestaurant.co.uk/wine
La Trompette|Chiswick|West|French & European|£25 lunch / £50 dinner|public|Rates per 75cl. Maximum four standard bottles or two magnums per table. Optional 12.5% service is additional. Tell the restaurant when booking; ask for magnum pricing.|https://www.latrompette.co.uk/wine/
Maison François|St James’s|Central|French brasserie|Free Sunday dinner|public|Published offer applies to Sunday dinner reservations from 16:00. Other services, bottle sizes and limits are not established. Confirm the offer when booking.|https://www.maisonfrancois.london/
Pied à Terre|Fitzrovia|Central|French fine dining|£55 wine / £80 sparkling|public|Wine rate is per 75cl. Maximum two bottles per table, with an expectation to purchase from the wine list. Unavailable on special occasions such as Valentine’s Day. Agree the arrangement before your visit.|https://www.pied-a-terre.co.uk/food-and-drink
Trishna|Marylebone|Central|Indian coastal cooking|£40 per 75cl|public|Maximum two bottles per reservation. Corkage is not available in the private dining room. Policy source is a May 2025 FAQ; reconfirm when booking.|https://www.trishnalondon.com/wp-content/uploads/2025/05/May-2025-Trishna-FAQ.pdf
Fallow|St James’s|Central|Modern British|£50 still / £90 sparkling|public|Rates per 75cl, only for wines absent from the restaurant’s list. Important: premium fine wines are charged at 50% of average value, at management discretion. Management may refuse corkage. Agree the exact fee before booking.|https://fallowrestaurant.com/faq/
The Harwood Arms|Fulham|West|British gastropub|£40 · free Friday lunch|public|£40 per 75cl, one bottle per person. Friday lunch corkage is free except in December. Confirm availability and any additional terms before booking.|https://harwoodarms.com/
Hawksmoor Borough|Borough|South|Steak & seafood|£5 Monday / £25 other days|public|Monday offer applies all day. Group policy states £25 per cork Tuesday to Sunday, any wine style or bottle size. This listing is the Borough branch, not a count of every London Hawksmoor.|https://thehawksmoor.com/wine-club/
Tayyabs|Whitechapel|East|Punjabi|BYO welcome · fee unknown|public|The official site explicitly welcomes guests to bring a bottle. A current fee, bottle limit and size allowance were not published in the material checked. Do not assume corkage is free.|https://www.tayyabs.co.uk/
Cabotte|City|City|French|Friday: first bottle free|public|Official post dated 30 May 2025 says you and a guest can enjoy a first bottle corkage-free on Fridays, with a second bottle at £30. This is a dated promotion: confirm it is still running. Other-day fees and bottle limits are not established.|https://www.cabotte.co.uk/blog/2025/5/30/enjoy-byo-fridays-in-the-heart-of-the-city
The Clove Club|Shoreditch|East|Modern British|£75 per bottle|public|One bottle of wine per two guests. Service charge is additional. Bottle format is not specified in the published clause; confirm before bringing a larger bottle.|https://www.thecloveclub.com/faq
Luca|Clerkenwell|Central|Italian|£50 per bottle|public|Maximum two bottles. The official site footer states the policy. Bottle format, service-charge treatment and any day restrictions should be confirmed.|https://luca.restaurant/
Trinity|Clapham|South|Seasonal modern cooking|£40 still · free Sunday evening|public|Downstairs only: £20/375ml; £40 still/750ml; £70 still magnum; £50 Champagne/750ml; £90 Champagne magnum. Fees waived Sunday evenings. One bottle per two guests; no wines already on the list; notify when confirming. Service is additional. No corkage Upstairs at Trinity.|https://trinityrestaurant.co.uk/wp-content/uploads/2026/01/Corkage-Policy-for-2026.pdf.pdf
Chez Bruce|Wandsworth Common|South|French & Mediterranean|£25 lunch / £50 dinner|public|Per 75cl bottle, one per guest and maximum four per table. Optional 12.5% service is additional. Notify the restaurant when booking if possible. No free-Sunday offer verified.|https://www.chezbruce.co.uk/wine/
Da Terra|Bethnal Green|East|Brazilian & Italian influences|£70 per 750ml|public|£40 per 375ml bottle. The FAQ does not state a bottle cap or service-charge treatment; check with the restaurant.|https://www.daterra.co.uk/faq/
Sune|Broadway Market|East|Menu to check with restaurant|£35 still / £45 sparkling|public|£65 per magnum. Special bottles are welcome; no bottle cap is published in the policy checked. General discretionary service is 13.5%; ask how this applies to corkage.|https://www.sune.restaurant/needtoknow
Restaurant Story|London Bridge|South|British tasting menu|£65 per 750ml|public|One bottle per two guests. Service-charge treatment is not stated in the published clause. Confirm the policy with your reservation.|https://restaurantstory.co.uk/useful-information/
The French Table|Surbiton|South|Contemporary French|£30 still / £40 sparkling|public|Standard 75cl bottles; magnums £60. Maximum two standard bottles or one magnum per reservation regardless of party size. 12.5% service is additional. Mention corkage when booking; check sparkling-magnum terms.|https://www.thefrenchtable.co.uk/wine
Noizé|Fitzrovia|Central|French bistro|BYO welcome · ask for fee|public|The official site encourages bringing wine for a small corkage fee, but the current amount, bottle cap and day restrictions were not established. Ask before booking; older third-party prices are not used here.|https://www.noize-restaurant.co.uk/about
The Ninth|Fitzrovia|Central|French & Mediterranean|Free corkage on Monday|public|Up to one bottle per person, maximum six bottles. Bottle size is unspecified. This is the published Monday offer; other-day fees are not officially verified. Reconfirm the offer with your reservation.|https://theninthlondon.com/news-recipes/
Cornus|Belgravia|Central|Modern European|£20 lunch / £40 dinner|public|Per 75cl bottle. No bottle limit, but the restaurant asks to know in advance. Larger-format and sparkling rates are not separately stated.|https://cornusrestaurant.co.uk/wine/
A. Wong|Victoria|Central|Chinese|£80 · bottle size to clarify|public|For a special bottle not available on the wine list. The FAQ literally states £80 per 70cl bottle and £160 per magnum. Confirm the unusual 70cl wording and your bottle’s fee with the restaurant. Bottle cap and day exclusions are not stated.|https://www.awong.co.uk/faq/
Galvin La Chapelle|Spitalfields|East|Mediterranean|£65 · agree exact fee ahead|public|One bottle of wine or Champagne per reservation. Fee may vary by wine and bottle size. Main dining room only, not private dining. Contact the restaurant in advance to agree the charge.|https://galvinrestaurants.com/galvin-la-chapelle/
Llewelyns|Herne Hill|South|Seasonal European|£30 still / £40 sparkling|public|Per 75cl. No bottle cap, wine-list exclusion or day limitation stated in the booking policy checked. Confirm arrangements when booking.|https://www.llewelyns-restaurant.co.uk/book
Bistro Union|Clapham|South|British bistro|£35 still / £40 sparkling|public|Per 75cl. Maximum two bottles per table, not already on the wine list. Notify in advance. A separate policy adds discretionary 12.5% service to bills.|https://bistrounion.co.uk/menus/
The Laundry|Brixton|South|European bistro|£25 · free Tuesday|public|No corkage charge on Tuesdays. Groups of 12 or more can only bring wine on Tuesdays. Bottle-size/category limits are unspecified. Discretionary 12.5% service applies to bills. Reconfirm the offer when booking.|https://thelaundrybrixton.com/frequently-asked-questions
Ploussard|Clapham Junction|South|Modern French|£35 per bottle|public|Reservations must be for a full dining experience, not drinks or snacks only. Bottle format, category, cap and service-charge treatment are not stated in the FAQ.|https://www.ploussardlondon.co.uk/faq
The Don|City|City|Modern European|Free Monday evening|public|Maximum two bottles per table; restaurant bookings only. Published promotion refers to a relaxed evening, not Monday lunch or private events. Formats and categories are unspecified. Confirm the offer is running.|https://thedonlondon.com/free-corkage-mondays/
Morchella|Clerkenwell|Central|Mediterranean|£36 still / £51 sparkling or sweet|public|The FAQ does not specify a bottle size or quantity cap. Check both with the restaurant rather than assuming a 750ml allowance.|https://www.morchelladining.co.uk/faqs
MAAI by Nikita|Clapham|South|Modern British|£30 per bottle|public|One bottle per two people, maximum four per booking. No Saturday evening corkage. Bottle size, sparkling terms and advance-notice requirement are not stated.|https://restaurantmaai.com/elementor-page-572/
Constance|Fulham|West|Modern British brasserie|£35 still / £40 sparkling|public|The public FAQ explicitly allows any number of bottles. Bottle size is unspecified. Normally closed Mondays except bank holidays; check matchday availability at Fulham Pier. Formerly Brasserie Constance.|https://constancerestaurant.com/
Brawn|Columbia Road|East|Seasonal European|£30 · private hire only evidence|events|Evidence is a November 2024 private-hire brochure: semi-private lunches Tuesday–Friday, 10–20 guests, 12–4pm, £2,000 food/beverage minimum and 12.5% service. £30 per 75cl. Not verified for an ordinary dinner booking. Reconfirm event terms.|https://www.brawn.co/wp-content/uploads/2024/11/A.C.T%5FBrawn%5FPrivate%5FHire%5FV6.pdf
Brunswick House|Vauxhall|South|Seasonal cooking|£35 still / £40 sparkling · events|events|Official 2026 private-event pack only: rates per 75cl including VAT, wine only, for an arrival reception and meal. General restaurant BYO is not officially verified. Do not apply these rates to an ordinary booking.|https://brunswickhouse.london/wp-content/uploads/2025/12/Private-Dining-Events-Info-Pack-2026.pdf
Cloth Fair|Smithfield|City|British & French|£25 · group/event evidence only|events|£25 per 75cl in the group-booking, private-hire and event brochure. Application to ordinary small-table dining is not established. Confirm current terms with the events team.|https://static1.squarespace.com/static/659c2c32d274403ce672b6eb/t/6890c9c3d88c3569e22cb6a6/1754319303019/Cloth%2BSpaces.pdf
Trivet|Bermondsey|South|Menu to check with restaurant|Members: free lunch corkage|members|Tasting Club members receive free lunchtime corkage, up to four bottles per table. Published annual membership is £240. General diner and dinner corkage policies are unknown. This is not a free public BYO offer.|https://trivetrestaurant.co.uk/trivet-tasting-club/
Darby’s|Nine Elms|South|Oysters & grill|£35 still / £45 sparkling · ask first|discretion|Per 75cl. All corkage arrangements, including the number of bottles permitted, are at management discretion. Agree in advance; no guaranteed allowance.|https://www.darbys-london.com/darbysmenus
Petersham Nurseries Restaurant|Richmond|South|Menu to check with restaurant|At manager’s discretion|discretion|The terms state corkage is at the manager’s discretion. No fee or allowance established. Confirm the current restaurant format and arrangement directly. The £30 cakeage fee is not a wine corkage fee.|https://petershamnurseries.com/terms-and-conditions/
Angler|Moorgate|City|Fish & shellfish|£50 wine / £100 sparkling · clarify|clarify|FAQ publishes these fees and excludes spirits, but also says not to bring outside food or drink. This contradiction is unresolved. Get explicit permission before taking wine; no format or quantity limit established.|https://anglerrestaurant.com/contact-us/'''
import re, unicodedata
from urllib.parse import urlsplit
PAIRS = {
'French': ['Restrained Chardonnay for butter-rich sauces and fish.', 'Mature Pinot Noir for poultry, mushrooms or lighter meat dishes.'],
'British': ['Fresh Chardonnay for fish or creamy sauces.', 'Cabernet-led Bordeaux for beef or slow-cooked meat.'],
'Mediterranean': ['Vermentino for seafood and herb-led plates.', 'Sangiovese for tomato-led dishes and grilled meat.'],
'Chinese': ['Off-dry Riesling for aromatic spice and heat.', 'Blanc de blancs Champagne for delicate dim sum.'],
'Indian': ['Off-dry Riesling for spice and chilli.', 'Dry sparkling rosé for rich, mixed plates.'],
'Punjabi': ['Off-dry Riesling for chilli and spice.', 'Low-tannin Gamay for grilled lamb.'],
'Italian': ['Verdicchio for seafood or vegetables.', 'Sangiovese for tomato sauces and meat.'],
'Steak': ['Mature Cabernet-led Bordeaux for beef.', 'Saline Chardonnay for seafood.'],
'Fish': ['Chablis for fish and shellfish.', 'Traditional-method sparkling for briny starters.'],
'Oysters': ['Muscadet or Chablis for oysters.', 'Mature Cabernet blend for grilled meat.']}
FREE = {'Kitchen W8':'Sunday evening','Maison François':'Sunday dinner','The Harwood Arms':'Friday lunch','Cabotte':'Friday, first bottle','Trinity':'Sunday evening','The Ninth':'Monday','The Laundry':'Tuesday','The Don':'Monday evening'}
SHOP = {
'Central': [('Berry Bros. & Rudd','63 Pall Mall, St James’s','https://www.bbr.com/our-shops/the-wine-shop'),('Hedonism','3–7 Davies Street, Mayfair','https://hedonism.co.uk/')],
'West': [('The Good Wine Shop','84 Chiswick High Road, Chiswick','https://www.thegoodwineshop.co.uk/pages/chiswick')],
'East': [('Bottle Apostle','95 Lauriston Road, Victoria Park Village','https://www.bottleapostle.com/shops.html'),('Shrine to the Vine','27 Broadway Market','https://shrinetothevine.co.uk/pages/london-wine-shops')],
'South': [('Bottle Apostle','59 Abbeville Road, Clapham','https://www.bottleapostle.com/clapham.html'),('The Good Wine Shop','56 Friars Stile Road, Richmond Hill','https://www.thegoodwineshop.co.uk/pages/shops')],
'City': [('Amathus','17–19 Leadenhall Market','https://www.amathusdrinks.com/city-store')]}
records = []
for line in ROWS.splitlines():
    name, neighbourhood, area, cuisine, fee, scope, policy, source = line.split('|')
    slug = re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',name).encode('ascii','ignore').decode().lower()).strip('-')
    pairs = []
    if not cuisine.startswith('Menu'):
        pairs = next((v for k,v in PAIRS.items() if k.lower() in cuisine.lower()), ['Textured dry Chenin Blanc for vegetable or white-meat courses.', 'Elegant Pinot Noir for richer seasonal dishes.'])
    website = 'https://www.clothrestaurants.com/cloth-restaurants-cloth-fair-london-reservations' if name == 'Cloth Fair' else f'https://{urlsplit(source).netloc}/'
    if name == 'Hawksmoor Borough': website = 'https://thehawksmoor.com/locations/borough/'
    if name.startswith('Noble Rot'): website = {'Noble Rot Soho':'https://noblerot.co.uk/restaurant/soho','Noble Rot Mayfair':'https://noblerot.co.uk/restaurant/mayfair','Noble Rot Lamb’s Conduit':'https://noblerot.co.uk/restaurant/lambs-conduit'}[name]
    records.append(dict(id=slug,website=website,name=name,neighbourhood=neighbourhood,area=area,cuisine=cuisine,fee=fee,scope=scope,policy=policy,source=source,checked='2026-09-13',freeOffer=FREE.get(name),pairings=pairs,merchants=[dict(name=n,address=a,url=u) for n,a,u in SHOP[area]]))
assert len(records)==42 and sum(r['scope']=='public' for r in records)==35
(ROOT/'data.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')
